### ISSUE TITLE
Alternative dataset link?

### ISSUE THREAD

**Issue by xjwxjw** [Khrylx/EgoPose#1]
Hi, I have tried many times downloading the dataset but all failed. Could you please provide other links for this dataset (e.g., BaiduYun), or split the large one into multiple smaller parts? Thank you very much!

**Comment by Khrylx** [comment]
Hi,

I'm now uploading to BaiduYun. It will take some time.

**Comment by xjwxjw** [comment]
OK, thx!

**Comment by Khrylx** [comment]
Are dropbox available in China?

**Comment by xjwxjw** [comment]
Yes, available. But I think the major issue is file size. Multiple smaller ones on Google Drive / Dropbox / BaiduYun are both OK.

**Comment by Khrylx** [comment]
Ok, I'm uploading the split dataset zips to this [link](https://drive.google.com/drive/folders/1gArkvMsyePQvSkWaV45708MchH1nDZZE?usp=sharing): https://drive.google.com/drive/folders/1gArkvMsyePQvSkWaV45708MchH1nDZZE?usp=sharing
Should be done in an hour.

**Comment by xjwxjw** [comment]
Great, thank you!

**Comment by Khrylx** [comment]
BaiduYun link for the dataset is here:
https://pan.baidu.com/s/18iSI84nFpCUdAqhuN1PcWw
passcode: ynui
