### ISSUE TITLE
About data preprocessing.

### ISSUE THREAD

**Issue by xjwxjw** [Khrylx/EgoPose#2]
I notice that gen_expert.py directly imports motion data from trajectory (*.p) files. What if I generate motion data from *.bvh files? Could you please provide the preprocessing script corresponding to *.bvh file? Thank you very much!

**Comment by Khrylx** [comment]
I added the code for converting BVH. I only tested on my BVH files.
https://github.com/Khrylx/EgoPose/blob/master/ego_pose/data_process/convert_clip.py

**Comment by xjwxjw** [comment]
Great! Thanks again!
