### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by xjwxjw** [Khrylx/EgoPose#3]
![egopose_example](https://user-images.githubusercontent.com/23734975/71435210-03d74680-2723-11ea-86d1-0cfb00de6e90.png)
Hello, the above figure is taken from your paper. It seems the whole sequence is recorded within one figure. How do you achieve this? Does the current repo contain relevant visualization code? Thank you very much!

**Comment by Khrylx** [comment]
In eval_pose.py, there is the "multi" option. You can give it a try.
https://github.com/Khrylx/EgoPose/blob/master/ego_pose/eval_pose.py#L20

**Comment by xjwxjw** [comment]
Get it. Thx!
