### ISSUE TITLE
Question on wpos to qpos conversion

### ISSUE THREAD

**Issue by Garfield-kh** [Khrylx/EgoPose#5]
Hi, 

Thank you very much for sharing this work, the result is very impressive to me.
May I ask a question on pose conversion?
I notice that the `qpos `is convert from `amc `file by `RFC/convert_cmu_mocap.py`,  and I want to convert the `wpos 3D pose` to `qpos` , which is the inverse of  function `get_ee_pos (full body version)`.
My plan is to convert `wpos `to `amc `format, but I am still a bit confusion on this step.
May I ask if you have solution or suggestion for this problem?

Btw,
When I run the code ego_mimic_eval.py, I met the problem below:
`$ python ego_pose/ego_mimic_eval.py --cfg subject_02 --iter 3000 `
`Traceback (most recent call last):`
`  File "ego_pose/ego_mimic_eval.py", line 41, in <module>`
`    env = HumanoidEnv(cfg)`
`  File "~xxx/EgoPose/ego_pose/envs/humanoid_v1.py", line 21, in __init__`
`    self.video_dir = cfg.video_dir`
`AttributeError: 'Config' object has no attribute 'video_dir'`

So I add it in  `EgoPose/ego_pose/utils/egomimic_config.py`
`self.video_dir = '%s/video' % self.cfg_dir`
`os.makedirs(self.video_dir, exist_ok=True)`
I think the same issue occurs in `ego_forecast_eval.py` due to cleaning process.
Hope it helps :)

Thank you~

**Comment by Khrylx** [comment]
Hello,

Thank you for finding the issue.
For the conversion question, I think you are trying to convert 3D joint positions into joint angles? That would require solving an inverse kinematics problem. You might want to look for some code and software (e.g., Unity) that can do that.

**Comment by Garfield-kh** [comment]
Thank you for the answering.
I just checked the inverse kinematics and noticed that it is exactly the inverse function of `get_ee_pos` .
While for my cases, I want to try new dataset on this code frame, which only requires conversion from `17-joints skeleton` 3D position (e.g., h36m) to joint angle representation.
I am new to unit quaternion, and I just treat it as a rotation matrix.
May I ask two questions for my cases? 

1. The solution is to caculate the rotation matrix from parent bond vector to son bond vector (e.g., from upper leg to lower leg), then convert into euler angle?
2. And for the root bone vector, the rotation matrix is from world coordinate to backbone vector (hip/root to upperback)?
